apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: fleetsim
  name: fleetsim
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "80"
    port: 80
    targetPort: 80
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    io.kompose.service: fleetsim
status:
  loadBalancer: {}
