apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: fleetsim
    app: fleetsim
  name: fleetsim
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fleetsim
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka_cluster: "true"
        io.kompose.service: fleetsim
    spec:
      containers:
      - image: local-fleetsim1x:latest
        imagePullPolicy: "Never"
        name: fleetsim
        ports:
        - containerPort: 8080
        - containerPort: 80
        - containerPort: 9090
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 512Mi
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
