apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: batch-layer
  name: batch-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: batch-layer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka_cluster: "true"
        io.kompose.service: batch-layer
    spec:
      containers:
      - image: local-batchlayer:latest
        imagePullPolicy: "Never"
        name: batch-layer
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
