apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-layer
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-layer
            image: horizoncr.azurecr.io/batch-layer:latest
          restartPolicy: OnFailure
