apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: speedlayer
  name: speedlayer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: speedlayer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka_cluster: "true"
        io.kompose.service: speedlayer
    spec:
      containers:
      - image: horizoncr.azurecr.io/speedlayer:1.0
        imagePullPolicy: ""
        name: speedlayer
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 1024Mi
      imagePullSecrets:
        - name: horizoncred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
